packages/auto-ipv6-ib: Setup dnsmasq for dhcpv6 (needs dnsmasq 2.62-rc2 or newer), fix default gw detection, use /112 for client networks, generate unique network from interface mac

diff --git a/auto-ipv6-ib/src/auto-ipv6 b/auto-ipv6-ib/src/auto-ipv6
--- a/auto-ipv6-ib/src/auto-ipv6
+++ b/auto-ipv6-ib/src/auto-ipv6
@@ -47,12 +47,35 @@ net_find_iface() {
         return 0
 }
 
-IP6_SUFIX="$(wget -q -O - http://[::1]:2006/hna | grep '::/0' | cut -d "$(printf "\t")" -f 2 | cut -d ':' -f 1-3)"
-[ -z $IP6_SUFIX ] && exit 0
-for i in $IP6_SUFIX ; do
+#we need to check all gateways in hna table and see which one is the default gw by looking at the etx for each gw
+
+local IPV6_GATEWAYS="$(wget -q -O - http://[::1]:2006/hna | grep '::/0' | cut -d "$(printf "\t")" -f 2)"
+
+local DEFAULT_ETX="1000000" # Use 1000 * 1000 here, because later we remove the decimal point in the etx from routes info
+for g in $IPV6_GATEWAYS; do
+        local GW_ETX="$(wget -q -O - http://[::1]:2006/routes | grep ^${g} | awk '{ print $4 }'| sed 's/\.//')"
+        if [ $GW_ETX -lt $DEFAULT_ETX ]; then
+                DEFAULT_ETX="$GW_ETX"
+                DEFAULT_GW="$g"
+        fi
+done
+
+#expand gw address (fill :: with appropriate amount of zeros)
+local colons="$(echo $DEFAULT_GW | grep -o ":" | wc -l)"
+local tofill=$(( 8 - $colons ))
+local filler=""
+
+for i in `seq 1 $tofill`; do
+	filler="0000:$filler"
+done
+
+IP6_SUFFIX=$(echo $DEFAULT_GW | sed "s/::/:$filler/" | cut -d ':' -f 1-4 )
+
+[ -z "$IP6_SUFFIX" ] && logger -t auto-ipv6 "No ipv6 gateway found. Either there is no IPv6 Gateway reachable or i could not connect to the txtinfo plugin. Exiting." && exit 1
+for i in $IP6_SUFFIX ; do
 	case $i in
 		fdca*) ;;
-		*) IP6_SUFIX=$i ;;
+		*) IP6_SUFFIX=$i ;;
 	esac
 done
 
@@ -60,7 +83,7 @@ config_load network
 local interfaces=""
 config_foreach net_find_iface interface
 
-local restart_radvd=0
+local restart_dnsmasq=0
 local restart_olsrd=0
 local hna6s=""
 
@@ -68,54 +91,81 @@ for i in $(echo $interfaces) ; do
 	[ "$(uci get network.$i.proto)" == "static" ] || continue
 	DEV="$(uci -q -p/var/state get network.$i.ifname)"
 	[ -z "$DEV" ]  && {
-		logger -t auto-ipv6 "uci Device Not Found IP6_SUFIX $IP6_SUFIX interfaces $i DEV $DEV check your uci config"
+		logger -t auto-ipv6 "uci Device Not Found IP6_SUFFIX $IP6_SUFFIX interfaces $i DEV $DEV check your uci config"
 		continue
 	}
 	grep -q "$DEV" /proc/net/dev || {
-		logger -t auto-ipv6 "proc Device Not Found IP6_SUFIX $IP6_SUFIX interfaces $i DEV $DEV check your uci config"
+		logger -t auto-ipv6 "proc Device Not Found IP6_SUFFIX $IP6_SUFFIX interfaces $i DEV $DEV check your uci config"
 		continue
 	}
 	IP6_UCI=$(uci get network.$i.ip6addr)
 	if [ $(echo $IP6_UCI | grep -i fdca) ] ; then
 		uci set network.$i.ip6addr_fdca="$IP6_UCI"
 	fi
-	IP6_OLDSUFIX="$(echo $IP6_UCI | cut -d ':' -f -3)"
+#	IP6_OLDSUFFIX="$(echo $IP6_UCI | cut -d ':' -f -3)"
+	IP6_OLDSUFFIX="$(echo $IP6_UCI | cut -d ':' -f -4)"
 	IP6_OLDUNIQ="$(echo $IP6_UCI | cut -d ':' -f 4)"
-	[ -z $IP6_OLDSUFIX ] || {
-		[ "$IP6_SUFIX" == "$IP6_OLDSUFIX" ] && ifconfig "$DEV" | grep -q -e "$IP6_SUFIX"".*1\/64" && {
-			hna6s="$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::"" $hna6s"
-			continue
-		}
-	}
-	#uci set "network.$i.ip6oldsufix=$IP6_SUFIX"
-	#Uniq 4Bybte from urandom
-	IP6_UNIQ="$(head -n 1 /dev/urandom 2>/dev/null | md5sum | cut -b 1-4)"
-	case $IP6_UNIQ in 
-		000*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 4) ;; 
-		00*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 3-4) ;; 
-		0*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 2-4) ;;
-	esac
+
+	[ "$IP6_SUFFIX" == "$IP6_OLDSUFFIX" ] && echo "no change detected" && exit
+#	[ -z $IP6_OLDSUFFIX ] || {
+#		[ "$IP6_SUFFIX" == "$IP6_OLDSUFFIX" ] && ifconfig "$DEV" | grep -q -e "$IP6_SUFFIX"".*1\/112" && {
+#			hna6s="$IP6_OLDSUFFIX"":""$IP6_OLDUNIQ""::"" $hna6s"
+#			continue
+#		}
+#	}
+	#uci set "network.$i.ip6oldSUFFIX=$IP6_SUFFIX"
+	# Uniq 4Bybte from urandom
+	# IP6_UNIQ="$(head -n 1 /dev/urandom 2>/dev/null | md5sum | cut -b 1-4)"
+
+	# Uniq 16 bit from last two octets of ipv4 address of this interface
+	#local ipv4addr=$(uci -q -p/var/state get network.$i.ipaddr)
+	#local o3=$(echo $ipv4addr | cut -d '.' -f 3)
+	#local o4=$(echo $ipv4addr | cut -d '.' -f 4)
+	#IP6_UNIQ="$(printf '%02x' $o3)$(printf '%02x' $o4)"
+
+	# Uniq parts from mac / works with /112 netmasks
+	local mac="$(ifconfig $DEV |grep HWaddr | awk '{ print $5 '})"
+	local IP6_UNIQ="$(echo $mac | awk -F: '{ print $1$2":"$3$4":"$5$6 }')"
+	echo "IP6_UNIQ $IP6_UNIQ"
+
+#	case $IP6_UNIQ in 
+#		000*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 4) ;; 
+#		00*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 3-4) ;; 
+#		0*) IP6_UNIQ=$(echo $IP6_UNIQ | cut -b 2-4) ;;
+#	esac
+
 	#uci set "network.$i.ip6olduniq=$IP6_UNIQ"
 	#uci commit network
-	[ -z $IP6_OLDSUFIX ] || {
-		ifconfig "$DEV" del "$IP6_OLDSUFIX"":""$IP6_OLDUNIQ""::1/64"
-	}
+
+#	[ -z $IP6_OLDSUFFIX ] || {
+#		ifconfig "$DEV" del "$IP6_OLDSUFFIX"":""$IP6_OLDUNIQ""::1/64"
+#	}
+
 	for j in $(ifconfig $DEV | grep Scope:Global | cut -d ' ' -f 13 ) ; do
 		ifconfig "$DEV" del "$j"
 	done
+
 	sysctl -w "net.ipv6.conf.$DEV.autoconf=0"
 	sysctl -w "net.ipv6.conf.$DEV.accept_redirects=0"
 	sysctl -w "net.ipv6.conf.$DEV.accept_ra=0"
 	sysctl -w "net.ipv6.conf.$DEV.accept_ra_defrtr=0"
 	sysctl -w "net.ipv6.conf.$DEV.accept_ra_pinfo=0"
 	sysctl -w "net.ipv6.conf.$DEV.accept_source_route=0"
-	ifconfig "$DEV" add "$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
-	uci -P /var/state set network.$i.ip6addr="$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
-	uci set network.$i.ip6addr="$IP6_SUFIX"":""$IP6_UNIQ""::1/64"
-	uci commit network
-	hna6s="$IP6_SUFIX"":""$IP6_UNIQ""::"" $hna6s"
 
-	restart_radvd=1
+#	IP6_ADDRESS="${IP6_SUFFIX}:${IP6_UNIQ}::${COUNTER}:1/112"
+	IP6_ADDRESS="${IP6_SUFFIX}:${IP6_UNIQ}:1/112"
+	echo "IP_ADDRESS for interface $DEV is $IP6_ADDRESS"
+	ifconfig "$DEV" add $IP6_ADDRESS
+	uci -P /var/state set network.$i.ip6addr="$IP6_ADDRESS"
+	uci set network.$i.ip6addr="$IP6_ADDRESS"
+	uci commit network
+	hna6s="$IP6_SUFFIX"":""$IP6_UNIQ""::"" $hna6s"
+	# Write /etc/dnsmasq.conf with our suffixes
+	sed -i "/${IP6_OLDSUFFIX}:${IP6_UNIQ}/d" /etc/dnsmasq.conf
+#	echo "dhcp-range=$DEV,$IP6_SUFFIX:$IP6_UNIQ::$COUNTER:100,$IP6_SUFFIX:$IP6_UNIQ::$COUNTER:100,112,300" >> /etc/dnsmasq.conf
+	echo "dhcp-range=$DEV,$IP6_SUFFIX:$IP6_UNIQ:100,$IP6_SUFFIX:$IP6_UNIQ:1000,112,300" >> /etc/dnsmasq.conf
+	restart_dnsmasq=1
+#	COUNTER="$(($COUNTER + 1))"
 done
 
 if [ "6and4" == "$(uci get olsrd.@olsrd[0].IpVersion)" ] ; then
@@ -126,7 +176,7 @@ if [ "6and4" == "$(uci get olsrd.@olsrd[0].IpVersion)" ] ; then
 		config_foreach olsrd_find_hna6 Hna6 $i
 		if [ "$neta" == "" ] ; then
 			uci add olsrd Hna6
-			uci set "olsrd.@Hna6[-1].prefix=64"
+			uci set "olsrd.@Hna6[-1].prefix=112"
 			uci set "olsrd.@Hna6[-1].netaddr=""$i"
 			uci commit olsrd
 			restart_olsrd=1
@@ -143,19 +193,21 @@ if [ "6and4" == "$(uci get olsrd.@olsrd[0].IpVersion)" ] ; then
 	done
 fi
 
+# clear all config variables here. else they will leak into the olsrd init script
+config_clear
 
-if [ $restart_radvd -eq 1 ] ; then
-	if ! [ -z "$(pidof radvd)" ] ; then
-		/etc/init.d/radvd stop
-		killall -9 radvd
-		/etc/init.d/radvd start
+
+if [ $restart_dnsmasq -eq 1 ] ; then
+	if ! [ -z "$(pidof dnsmasq)" ] ; then
+		logger -t auto-ipv6 "Restarting dnsmasq..."
+		/etc/init.d/dnsmasq restart
 	fi
 fi
+
 if [ $restart_olsrd -eq 1 ] ; then
 	if ! [ -z "$(pidof olsrd)" ] ; then
-		/etc/init.d/olsrd stop
-		killall -9 olsrd
-		/etc/init.d/olsrd start
+		logger -t auto-ipv6 "Restarting olsrd..."
+		/etc/init.d/olsrd restart
 	fi
 fi
 
