packages/auto-ipv6-ib: simplify hna setup

diff --git a/auto-ipv6-ib/src/auto-ipv6 b/auto-ipv6-ib/src/auto-ipv6
--- a/auto-ipv6-ib/src/auto-ipv6
+++ b/auto-ipv6-ib/src/auto-ipv6
@@ -1,53 +1,37 @@
 #!/bin/sh
+. /lib/functions.sh
+
+DEBUG=1
+dns_servers="[::]"
+local dnsmasq_conf="/etc/dnsmasq.conf"
+
 # Do not run this script more than once at a time
 local pid="$(pidof auto-ipv6)"
 local count=0
 for p in pid; do
 	count=$(expr $count + 1)
 done
-[ $count -gt 1 ] && echo "$(pidof auto-ipv6)" && echo "already running" && exit 1
-DEBUG=1
-dns_servers="[::]"
-local dnsmasq_conf="/etc/dnsmasq.conf"
+[ $count -gt 1 ] && logger -s -t auto-ipv6 "autoipv6 is already running, exit." && exit 1
 
-. /lib/functions.sh
 config_load autoipv6
 local enabled
 config_get enabled "olsr_node" enabled
-[ "$enabled" == 1 ] || exit 0
+[ "$enabled" == 1 ] || {
+	[ "$DEBUG" == 1 ] && logger -s -t auto-ipv6 "autoipv6 is disabled, not running the script."
+	exit 0
+}
+
 local mode
 config_get mode "olsr_node" mode
 
-#set -x
-olsrd_clear_hna6() {
-	uci delete 'olsrd.@Hna6[-1]'
-	return 0
-}
-olsrd_find_hna6() {
-	local cfg="$1"
-	local netaddr="$2"
-	config_get Netaddr $cfg netaddr
-	if [ "$Netaddr" == "$netaddr" ] ; then
-		neta="$count $neta"
-	fi
-	count=$((count+1))
-	return 0
-}
-
-olsrd_search_hna6() {
-	local cfg="$1"
-	local found="0"
-	config_get Netaddr $cfg netaddr
-	for i in $hna6s ; do
-		if [ "$Netaddr" == "$i" ] ; then
-			found="1"
-		fi
-	done
-	if [ "$found" == "0" ] ; then
-		neta="$count $neta"
-	fi
-	count=$((count+1))
-	return 0
+olsrd_add_hna() {
+	local iface="$1"
+	local name="$2"
+	local net="$3"
+	local mask="${4:=64}"
+	uci set olsrd.$name=Hna6
+	uci set olsrd.$name.netaddr="${net}"
+	uci set olsrd.$name.prefix="$mask"
 }
 
 net_find_iface() {
@@ -70,18 +54,19 @@ local hnainfo
 hnainfo="$(wget -q http://[::1]:2006/hna -O -)"
 ret=$?
 if [ $ret -ne 0 ]; then
-	logger -s -t auto-ipv6 "Could not connect to the txtinfo plugin, exiting."
-	txtinfo=0
+	logger -s -t auto-ipv6 "Error: Could not connect to the txtinfo plugin."
 fi
 
 local IPV6_GATEWAYS="$(wget -q http://[::1]:2006/hna -O - | grep '2000::/3' | cut -d "$(printf "\t")" -f 2)"
-local DEFAULT_ETX="1000000" # Use 1000 * 1000 here, because later we remove the decimal point in the etx from routes info
+local DEFAULT_ETX=1000000 # Use 1000 * 1000 here, because later we remove the decimal point in the etx from routes info
 for g in $IPV6_GATEWAYS; do
         local GW_ETX="$(wget -q -O - http://[::1]:2006/routes | grep ^${g} | awk '{ print $4 }'| sed 's/\.//')"
-        if [ $GW_ETX -lt $DEFAULT_ETX ]; then
-                DEFAULT_ETX="$GW_ETX"
-                DEFAULT_GW="$g"
-        fi
+        if [ -n "$GW_ETX" ]; then
+		if [ $GW_ETX -lt $DEFAULT_ETX ]; then
+			DEFAULT_ETX="$GW_ETX"
+			DEFAULT_GW="$g"
+	        fi
+	fi
 done
 
 #expand gw address (fill :: with appropriate amount of zeros)
@@ -106,7 +91,6 @@ done
 local restart_dnsmasq=0
 local dnsmasq_options=""
 local restart_olsrd=0
-local hna6s=""
 local ra=0
 
 local interfaces=""
@@ -141,7 +125,6 @@ for i in $(echo $interfaces) ; do
 		ula_net=$(echo $ulanew | sed 's/::.*//')
 	fi
 	ula_ip6addr=$(echo $ulanew | cut -d "/" -f 0)
-	echo ula_ip6addr $ula_ip6addr
 
         if [ -z "$ula" ]; then
 		uci batch <<- EOF
@@ -160,13 +143,8 @@ for i in $(echo $interfaces) ; do
 			restart_dnsmasq=1
 		fi
 		# add olsrd hna6 entry for ula
-		uci add olsrd Hna6
-		uci set olsrd.@Hna6[-1].prefix="64"
-		uci set olsrd.@Hna6[-1].netaddr="${ula_net}::"
-		uci commit olsrd
+		olsrd_add_hna $i autoipv6${i}ula ${ula_net}:: 64
 		restart_olsrd=1
-
-		
 		[ $DEBUG -eq 1 ] && logger -s -t auto-ipv6 "Added ULA-alias ip $ulanew for ${i}." 
 	fi
 
@@ -187,9 +165,8 @@ for i in $(echo $interfaces) ; do
 	fi
 	IP6_OLDUNIQ="$(echo $IP6_UCI | cut -d ':' -f 4)"
 
-	echo $IP6_SUFFIX $IP6_OLDSUFFIX
 	if [ "$IP6_SUFFIX" == "$IP6_OLDSUFFIX" ]; then
-		[ $DEBUG -eq 1 ] && logger -s -t auto-ipv6 "no change detected"
+		[ $DEBUG -eq 1 ] && [ "$DEBUG" -eq 1 ] && logger -s -t auto-ipv6 "no change detected. Prefix is still $IP6_SUFFIX"
 		break
 	fi
 
@@ -200,12 +177,16 @@ for i in $(echo $interfaces) ; do
 		IP6_UNIQ="$(echo $mac | awk -F: '{ print $1$2":"$3$4":"$5$6 }')"
 		echo "IP6_UNIQ $IP6_UNIQ"
 		IP6_ADDRESS="${IP6_SUFFIX}:${IP6_UNIQ}:1/112"
+		olsrd_add_hna $i autoipv6${i} ${IP6_SUFFIX}:${IP6_UNIQ}:: 112
+		restart_olsrd=1
 	fi
 
 	if [ "$mode" = "random" ] || [ "$mode" = "fromv4" ]; then
 		[ -z $IP6_OLDSUFFIX ] || {
 			[ "$IP6_SUFFIX" == "$IP6_OLDSUFFIX" ] && ifconfig "$DEV" | grep -q -e "$IP6_SUFFIX"".*1\/64" && {
 			hna6s="$IP6_OLDSUFFIX"":""$IP6_OLDUNIQ""::"" $hna6s"
+			olsrd_add_hna $i autoipv6${i}old ${IP6_OLDSUFFIX}:${IP6_OLDUNIQ}:: 64
+			restart_olsrd=1
 			continue
 			}
 		}
@@ -218,7 +199,6 @@ for i in $(echo $interfaces) ; do
                 if [ "$mode" = "fromv4" ]; then
 			# Uniq 16 bit from last two octets of ipv4 address of this interface
 			IP6_UNIQ="$(ipv6uniq_from_v4 $i)"
-			echo $IP6_UNIQ
 		fi
 
 		case $IP6_UNIQ in 
@@ -236,6 +216,9 @@ for i in $(echo $interfaces) ; do
 		IP6_ADDRESS="${IP6_SUFFIX}:${IP6_UNIQ}::1/64"
 		dns_servers="$dns_servers,[$ula_ip6addr]"
 	fi
+
+	olsrd_add_hna $i autoipv6${i} ${IP6_SUFFIX}:${IP6_UNIQ}:: 64
+	restart_olsrd=1
 
 	for j in $(ifconfig $DEV | grep Scope:Global | cut -d ' ' -f 13 ) ; do
 		ifconfig "$DEV" del "$j"
@@ -267,38 +250,11 @@ for i in $(echo $interfaces) ; do
 	uci -P /var/state set network.$i.ip6addr="$IP6_ADDRESS"
 	uci set network.$i.ip6addr="$IP6_ADDRESS"
 	uci commit network
-	hna6s="$IP6_SUFFIX"":""$IP6_UNIQ""::"" $hna6s"
-        hna6s="${ula_net}:: $hna6s"
 	restart_dnsmasq=1
 done
 
 if [ "6and4" == "$(uci get olsrd.@olsrd[0].IpVersion)" ] ; then
-	config_load olsrd
-	for i in $hna6s ; do
-		local neta=""
-		local count=0
-		config_foreach olsrd_find_hna6 Hna6 $i
-		if [ "$neta" == "" ] ; then
-			uci add olsrd Hna6
-			if [ "$mode" = "dhcpv6" ]; then
-				uci set "olsrd.@Hna6[-1].prefix=112"
-			else
-				uci set "olsrd.@Hna6[-1].prefix=64"
-			fi
-			uci set "olsrd.@Hna6[-1].netaddr=""$i"
-			uci commit olsrd
-			restart_olsrd=1
-		fi
-	done
-
-	local neta=""
-	local count=0
-	config_foreach olsrd_search_hna6 Hna6
-	for i in $neta ; do
-		uci delete "olsrd.@Hna6["$i"]"
-		uci commit olsrd
-		restart_olsrd=1
-	done
+	uci commit olsrd
 fi
 
 # clear all config variables here. else they will leak into the olsrd init script
